### ISSUE TITLE
Do you prevent the game state from advancing while waiting for a slow client?

### ISSUE THREAD

**Issue by garymm** [mikelma/craftium#1]
Hi,
If I have a very slow client (agent), is there anything that prevents the server game loop from advancing the game state?
Say my python code takes a very long time to call `step()`. Is there anything that forces the game to not continue to advance between calls to `step()`?

**Comment by mikelma** [comment]
Hi! Yes, craftium should block server updating until the client responds. I have made some tests on this and seems to work, but further testing would be nice. Have you tried it?

**Comment by garymm** [comment]
How did you implement it? Can you show me the commits or the lines of code?

**Comment by garymm** [comment]
I have not tried it.
