### ISSUE TITLE
Suggestion to separate RL training dependencies

### ISSUE THREAD

**Issue by kaixin96** [mikelma/craftium#2]
Thank you for making Minetest a gymnasium environment! It's awesome!

I have a suggestion regarding the setup. Would you consider separating the dependencies for the RL training part (e.g., PyTorch and SB3) from the dependencies for the environment? I believe this would enhance flexibility.

**Comment by mikelma** [comment]
Thanks!! This is a great idea, I'll try to implement it in the next few days.

**Comment by kaixin96** [comment]
Thank you! Looking forward to it!

**Comment by mikelma** [comment]
Commits 1a7505a5b62a3ba1945aeffa3408abb9b0d85285 and fb1733815f41b0e3ba848fbf52f7cdbbb35e9d7d solve this issue!
